project_id = "rwhhabwgnkqjxcqwpcev"

[functions.check-expiring-favorites]
verify_jwt = false

[functions.expire-pending-pins]
verify_jwt = false

[functions.match-taxonomy]
verify_jwt = false

[functions.provision-brand]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false