-- =========================================================================
-- FASE B — Commit 4 — APLICADO em 2026-05-13
-- Migration: supabase/migrations/20260513222015_*.sql
--
-- Removidos 18 wrappers de compatibilidade duelo_* → campeonato_*:
--   • 13 originais da Fase B
--   • 5 do Bloco B (Fase B-Cleanup)
--
-- Sanidade pós-drop (public.duelo_*):
--   - duelo_increment_bracket_rides   (trigger function — fora de escopo)
--   - duelo_update_standings_from_ride (trigger function — fora de escopo)
--
-- Nenhum wrapper/alias remanescente. Arquivo mantido como histórico.
-- =========================================================================
