import {
  MapPin, Settings2, ShoppingBag, Coins, Car, Wallet, Tag,
} from "lucide-react";
import type { EtapaOnboarding } from "../types/tipos_onboarding";

export const ETAPAS_ONBOARDING: EtapaOnboarding[] = [
  {
    id: "1",
    fase: "Criar",
    icone: MapPin,
    cor: "bg-teal-100 text-teal-700 dark:bg-teal-950 dark:text-teal-300",
    titulo: "Criar a Cidade",
    descricao: "Cadastre a nova cidade na plataforma.",
    rota: "/brand-branches/new",
    chaveValidacao: "cidadeCriada",
    passos: [
      "Acesse Cidades → Minhas Cidades.",
      "Clique em 'Nova Cidade'.",
      "Selecione o Estado e digite o nome da cidade.",
      "O sistema preenche slug, timezone e coordenadas automaticamente.",
      "Clique em 'Criar Cidade' para salvar.",
    ],
    dicas: [
      "As coordenadas são preenchidas automaticamente — não é necessário editar.",
      "O slug é gerado a partir do nome da cidade.",
    ],
  },
  {
    id: "2",
    fase: "Modelo",
    icone: Settings2,
    cor: "bg-purple-100 text-purple-700 dark:bg-purple-950 dark:text-purple-300",
    titulo: "Definir o Modelo de Negócio",
    descricao: "Escolha se a cidade opera com motoristas, passageiros ou ambos.",
    rota: "/regras-resgate",
    chaveValidacao: "modeloNegocio",
    passos: [
      "Acesse Cidades → Regras de Resgate.",
      "Selecione a cidade no filtro.",
      "Escolha o modelo: Apenas Motorista, Apenas Passageiro ou Ambos.",
      "O modelo define menus e funcionalidades disponíveis.",
      "Clique em 'Salvar'.",
    ],
    dicas: [
      "Novas cidades herdam o modelo padrão da marca.",
      "Você pode alterar o modelo a qualquer momento.",
    ],
  },
  {
    id: "3",
    fase: "Parceiros",
    icone: ShoppingBag,
    cor: "bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-300",
    titulo: "Cadastrar Parceiros",
    descricao: "Vincule pelo menos 1 parceiro ativo à cidade.",
    rota: "/stores",
    chaveValidacao: "parceiros",
    passos: [
      "Acesse Gestão Comercial → Parceiros.",
      "Crie um novo parceiro ou edite um existente.",
      "Selecione a nova cidade no campo 'Cidade'.",
      "Certifique-se de que o parceiro está ativo e aprovado.",
    ],
    dicas: [
      "Você pode importar parceiros em lote via Importação de Dados.",
      "Parceiros inativos não contam para a validação.",
    ],
  },
  {
    id: "4",
    fase: "Pontos",
    icone: Coins,
    cor: "bg-yellow-100 text-yellow-700 dark:bg-yellow-950 dark:text-yellow-300",
    titulo: "Configurar Regras de Pontos",
    descricao: "Defina como os pontos são creditados na cidade.",
    rota: "/points-rules",
    chaveValidacao: "regrasPontos",
    condicional: "PASSENGER",
    passos: [
      "Acesse Programa de Fidelidade → Regras de Fidelidade.",
      "Filtre pela nova cidade.",
      "Defina a taxa de pontos por R$ gasto.",
      "Configure limites e regras específicas se necessário.",
    ],
    dicas: [
      "Cidades novas herdam a regra padrão da marca.",
      "Use regras diferentes para incentivar regiões com menos engajamento.",
    ],
  },
  {
    id: "5",
    fase: "Mobilidade",
    icone: Car,
    cor: "bg-indigo-100 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300",
    titulo: "Ativar Integração de Mobilidade",
    descricao: "Configure a API para pontuar corridas automaticamente.",
    rota: "/machine-integration",
    chaveValidacao: "integracaoMobilidade",
    condicional: "DRIVER",
    passos: [
      "Acesse Integrações & API → Integração Mobilidade.",
      "Selecione a cidade.",
      "Preencha credenciais (Basic Auth + API Key).",
      "Salve para registrar o webhook automaticamente.",
      "Teste no Lab de Webhook.",
    ],
    dicas: [
      "Sem a integração ativa, corridas não geram pontos automaticamente.",
      "Consulte o Guia da API para detalhes completos.",
    ],
  },
  {
    id: "6",
    fase: "Carteira",
    icone: Wallet,
    cor: "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300",
    titulo: "Carregar Carteira de Pontos",
    descricao: "Garanta saldo na carteira da cidade para distribuir pontos.",
    rota: "/brand-branches",
    chaveValidacao: "carteiraPontos",
    condicional: "DRIVER",
    passos: [
      "Acesse Cidades → Minhas Cidades.",
      "Clique na cidade para editar.",
      "Verifique o saldo da carteira de pontos.",
      "Carregue um saldo inicial se necessário.",
    ],
    dicas: [
      "A carteira é criada automaticamente ao criar a cidade.",
      "O sistema permite saldo negativo, mas é recomendável manter saldo positivo.",
    ],
  },
  {
    id: "7",
    fase: "Ofertas",
    icone: Tag,
    cor: "bg-pink-100 text-pink-700 dark:bg-pink-950 dark:text-pink-300",
    titulo: "Criar Ofertas Ativas",
    descricao: "Cadastre pelo menos 1 oferta ativa para os clientes.",
    rota: "/offers",
    chaveValidacao: "ofertasAtivas",
    condicional: "PASSENGER",
    passos: [
      "Acesse Gestão Comercial → Ofertas.",
      "Crie uma nova oferta vinculada a um parceiro da cidade.",
      "Defina desconto, valor de resgate e prazo.",
      "Publique a oferta como 'Ativa'.",
    ],
    dicas: [
      "Ofertas inativas não aparecem para os clientes.",
      "Você pode clonar ofertas de outra cidade para agilizar.",
    ],
  },
];
