
ALTER TYPE ledger_reference_type ADD VALUE IF NOT EXISTS 'SIDE_BET_RESERVE';
ALTER TYPE ledger_reference_type ADD VALUE IF NOT EXISTS 'SIDE_BET_WIN';
ALTER TYPE ledger_reference_type ADD VALUE IF NOT EXISTS 'SIDE_BET_REFUND';
ALTER TYPE ledger_reference_type ADD VALUE IF NOT EXISTS 'SIDE_BET_DUEL_BONUS';
ALTER TYPE ledger_reference_type ADD VALUE IF NOT EXISTS 'BELT_PRIZE';
ALTER TYPE ledger_reference_type ADD VALUE IF NOT EXISTS 'DUEL_SETTLEMENT';
